apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user

resources:
  - namespace.yaml
  - auth-deployment.yaml
  - auth-service.yaml
  - user-deployment.yaml
  - user-service.yaml
  - auth-app-network-policy.yaml
  - user-app-network-policy.yaml
