apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
  namespace: user
  labels:
    app: user-app-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app-pod
  template:
    metadata:
      labels:
        app: user-app-pod
    spec:
      containers:
      - name: user-app-container-name
        image: hbc08/k8s-user-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: VERSION
          value: "2.0"
        - name: HELLO_WORLD_SERVICE_URL
          value: "http://xinchao-app-service.hello-world:8889"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"